### ISSUE TITLE
Modifier + direction causes Silvius client to crash

### ISSUE THREAD

**Issue by crypdick** [dwks/silvius#22]
This makes it hard to navigate i3. Example:

```
control left 
> control left
[control, left, END]
 chain {
     mod_plus_key ['ctrl'] {
         movement [left]
     }
 }
Traceback (most recent call last):
  File "grammar/main.py", line 31, in <module>
    execute(ast, f == sys.stdin)
  File "/home/shit/bin/voice2code/silvius-crypdick/grammar/execute.py", line 103, in execute
    ExecuteCommands(ast, real)
  File "/home/shit/bin/voice2code/silvius-crypdick/grammar/execute.py", line 12, in __init__
    self.postorder_flat()
  File "/home/shit/bin/voice2code/silvius-crypdick/grammar/execute.py", line 26, in postorder_flat
    func(node)
  File "/home/shit/bin/voice2code/silvius-crypdick/grammar/execute.py", line 32, in n_chain
    self.postorder_flat(n)
  File "/home/shit/bin/voice2code/silvius-crypdick/grammar/execute.py", line 26, in postorder_flat
    func(node)
  File "/home/shit/bin/voice2code/silvius-crypdick/grammar/execute.py", line 38, in n_mod_plus_key
    self.automator.mod_plus_key(node.meta, node.children[0].meta[0])
  File "/home/shit/bin/voice2code/silvius-crypdick/grammar/execute.py", line 98, in mod_plus_key
    if(len(k) > 1 and k != 'plus' and k != 'apostrophe' and k != 'period' and k != 'minus'): k = k.capitalize()
AttributeError: Token instance has no attribute '__len__'
super left 
Exception in thread WebSocketClient:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/shit/.local/lib/python2.7/site-packages/ws4py/websocket.py", line 528, in run
    if not self.once():
  File "/home/shit/.local/lib/python2.7/site-packages/ws4py/websocket.py", line 410, in once
    if not self.process(self.buf[:requested]):
  File "/home/shit/.local/lib/python2.7/site-packages/ws4py/websocket.py", line 480, in process
    self.received_message(s.message)
  File "stream/mic.py", line 113, in received_message
    sys.stdout.flush()
IOError: [Errno 32] Broken pipe
```

**Comment by dwks** [comment]
Fixed in #26. Please let me know if any other key combinations cause issues.
